layout_spectrum: 0.7669768
typography_spectrum: 0.4605735
color:
  saturation: 0.08243728
  lightness: 1
  brandStrength: 0.5591398
  brandColors:
    - '#000000'
    - '#00CCFF'
    - '#FF9933'
    - '#9A5C1F'
    - '#42270D'
  rhythmicContrast: 0.172043
name: Cupcakes and Photo Bombs
